name: Build Kotlin/Native
on:
  push:
    paths:
      - 'kotlin/**'
      - '.github/workflows/kotlin.yml'
  pull_request:
    paths:
      - 'kotlin/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Build Kotlin/Native binaries
        run: ./gradlew build
        working-directory: kotlin
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: kotlin-native
          path: kotlin/build/**
