name: Build Kotlin/Native
on:
  push:
    paths:
      - 'kotlin/**'
      - '.github/workflows/kotlin.yml'
  pull_request:
    paths:
      - 'kotlin/**'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Kotlin Native
        run: brew install kotlin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '9.6.1'
      - name: Build Kotlin/Native binaries
        run: gradle build
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: kotlin-native
          path: kotlin/build/bin/**
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          name: Kotlin Native ${{ github.ref_name }}
          files: kotlin/build/bin/**
