name: Build Node
on:
  push:
    paths:
      - 'node/**'
      - '.github/workflows/node.yml'
  pull_request:
    paths:
      - 'node/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm install
        working-directory: node
      - name: Build
        run: npm run build
        working-directory: node
      - name: Archive Build
        run: |
          tar -czf build.tar.gz -C dist .
        working-directory: node
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: node-build
          path: node/build.tar.gz
