name: Build Rust
on:
  push:
    paths:
      - 'rust/**'
      - '.github/workflows/rust.yml'
  pull_request:
    paths:
      - 'rust/**'
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build Rust binary
        run: cargo build --release --manifest-path Cargo.toml
        working-directory: rust
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: rust-binary
          path: rust/target/release/*
