name: Build Swift
on:
  push:
    paths:
      - 'swift/**'
      - '.github/workflows/swift.yml'
  pull_request:
    paths:
      - 'swift/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - name: Build Swift package
        run: swift build -c release
        working-directory: swift
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: swift-binary
          path: swift/.build/release/expando
